### ISSUE TITLE
Manifest build takes too long, then hangs

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/knowledge-graph-hub.github.io#16]
The most recent build on Jenkins seemed to be making progress, albeit slowly, then hung at this point after ~48 hrs:
```
00:19:25  The project kg-idg contains:
00:19:25  	2133 objects
00:19:25  	22 builds
00:19:25  	1 incorrectly named builds
00:19:25  		['raw']
00:19:25  	1 incorrectly structured builds
00:19:25  		['raw']
00:19:25  	22 builds with KGX format problems
00:19:25  		['20211029', '20211101', '20211112', '20211123', '20211201', '20211202', '20211207', '20211210', '20211213', '20211215', '20211221', '20211223', '20220101', '20220106', '20220107', '20220119', '20220201', '20220203', '20220204', '20220216', '20220223', 'raw']
00:19:25  Validating new builds for kg-covid-19...
00:19:25  Retrieving kg-covid-19/20200925/kg-covid-19.tar.gz...
00:19:35  Validating graph files with KGX...
```
I aborted the build after > 5 days in this state.

Manifest generation is expected to take a long time initially, as it's going to index and validate every graph on KG-Hub, but this time it appeared to get stuck.
Options:
* Push a new MANIFEST + logs to the remote after a batch rather than attempting to do all of them at once
* Skip validation for graphs older than a certain point
* Pre-populate a MANIFEST for the older versions by running MANIFEST generation locally first, then pushing to remote

**Comment by caufieldjh** [comment]
Reproduced the more recent issue locally - will make new issue because it is new behavior and I think it's unrelated to the other issue.

**Comment by caufieldjh** [comment]
Would really like MANIFEST builds to complete, so:
* Will not perform a full `kgx validate` on all new builds - just the most recent.
The existing behavior already ignores old builds (i.e., those already in the MANIFEST) for validation.
* Skip KG-COVID-19 graphs for validation, as they appear to be just large enough to pose an issue (or there are different problems).

**Comment by caufieldjh** [comment]
One file works! It still took 5 hours, but it finished, so that's nice.

**Comment by justaddcoffee** [comment]
@caufieldjh is this right - one graph takes 5 hours to process?

**Comment by caufieldjh** [comment]
Yes - most of that time is dedicated to `kgx validate`, and in turn that's much slower than it could be when there are numerous validation errors and a lot of log output (#13) - haven't found a solution for the logs yet, as the call to validate seems to ignore having the log output set to `dev/null` and any attempt to redirect STDOUT/STDERR

**Comment by caufieldjh** [comment]
Seems to be resolved now, as long as it doesn't have to do a full `kgx validate` on KG-COVID-10 or Eco-KG.
