### ISSUE TITLE
Minor tweaks - maybe we could change "Repository" to "Source code", and "Graph" to "Knowledge graph"

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/knowledge-graph-hub.github.io#28]
On [the landing page[(https://knowledge-graph-hub.github.io/), maybe we could change "Repository" to "Source code", and "Graph" to "Knowledge graph"? 

Unless you have wording you'd rather use @caufieldjh

**Comment by caufieldjh** [comment]
Sure - done in linked PR.
