### ISSUE TITLE
Landing page for KG-Hub

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/knowledge-graph-hub.github.io#3]
We want a landing page displaying all the graph resources, ideally grouped by project.
e.g., like the OBO Foundry landing page
@justaddcoffee

**Comment by justaddcoffee** [comment]
We could maybe crib code to make this landing page from OBOFoundry's awesome code here:
https://github.com/OBOFoundry/OBOFoundry.github.io

**Comment by justaddcoffee** [comment]
+1!
