### ISSUE TITLE
Broken links on KG-Hub.org homepage

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/knowledge-graph-hub.github.io#35]
These three links seem to be 404: 
https://github.com/Knowledge-Graph-Hub/knowledge-graph-hub.github.io/blob/5936ec91dc7ef7a41c5ddeddc6509b0ec522d75c/docs/index.html#L15
https://github.com/Knowledge-Graph-Hub/knowledge-graph-hub.github.io/blob/5936ec91dc7ef7a41c5ddeddc6509b0ec522d75c/docs/index.html#L16
https://github.com/Knowledge-Graph-Hub/knowledge-graph-hub.github.io/blob/5936ec91dc7ef7a41c5ddeddc6509b0ec522d75c/docs/index.html#L17

**Comment by caufieldjh** [comment]
Fixed by #36
