### ISSUE TITLE
add an entry for RNA-KG? 

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/knowledge-graph-hub.github.io#39]
Emanuele Cavelleri and Marco Mesiti et al from the Anacleto lab have built a KG that integrates RNA data (called aptly enough RNA-KG). 

We maybe could create an entry in the main table here pointing to the code, which lives here: 
https://github.com/AnacletoLAB/RNA-KG
~There are also links to ntriple files for the graph here, but they seem to be 404:
https://zenodo.org/records/10418431~
ntriples for the KG is here:
https://zenodo.org/records/10418431/files/RNA-KG.nt?download=1

For background, some slides describing their KG is [here](https://drive.google.com/file/d/1GGyyDhpVHdDVIQWVwaEeVhgm3r8qDuJs/view) and preprint is [here](https://doi.org/10.48550/arXiv.2312.00183). This is Pheknowlator-based, so no KGX TSV is available

**Comment by caufieldjh** [comment]
Added in #40
